name:               "Alex Antonov"
description:        "Software craftsman"

avatar:             "http://cs5792.vk.me/u83675669/-6/y_b1d7190e.jpg"
url:                "asiniy.com"
author:             ""
email:              ""
twitter:            "asiniy"
email:              "kaburbundokel11g@gmail.com"
github:             "asiniy"
stackoverflow:      "users/2926641/asiniy"

disqus:             "disqus_TcAs6ELJKq"

background:         "http://www.justocascante.com/images/painting/sea2.jpg"

paginate:           20
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate

destination:        "docs"
